#!/bin/bash
# source: "https://pkg.go.dev/github.com/gokcehan/lf"
source ~/.config/lf/cmds.sh

# Sets
set shell bash
set hidden true
set icons true

set previewer ./extras/preview.sh
set cleaner ./extras/clean.sh

set ignorecase true
set incsearch true

set mouse true # allow mouse input
set scrolloff 8


# Maps
##view/open the current file
map <enter> open
map l open
map e edit

##execute current file
map x $$f
map X !$f

##trash file
#map D trash "$f"
#map dd trash "$f"

##remove file
#map D rm "$f"
#map dd rm "$f"

##semicolon to enter cmds
#map ";" push ":"
#map ":" push ";"

##scroll up/down
map K scrollup
map J scrolldown

##mouse input
map <m-up> scrollup
map <m-down> scrolldown

# TODO:
## Find a way to use env vars in lf
