github.com:
    user: NYANLAUNCHER
    git_protocol: https
    users:
        NYANLAUNCHER: {oauth_token: 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}
    oauth_token: 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
