#!/bin/bash
# set shell aliases and functions
## designed for an interactive console

# Aliases
alias n="nvim"
alias rm="$HOME/.local/bin/trash"
alias rmf="/usr/bin/rm"
alias bf="brainfuck"
alias rsc="rustc"
alias rsup="rustup"
alias ncmp="ncmpcpp"
alias ardour="ardour7"
alias z="zathura"
alias luals="lua-language-server"
alias virtman="virt-manager"
alias su="sudo su"
alias gitinfo="onefetch"
# for drawing directed graphs
alias dg="/usr/bin/dot"

# let shell scripts use these aliases
#shopt -s expand_aliases

# Functions
dot() { git --git-dir=$HOME/.dotfiles --work-tree=$HOME $@; }
sudot() { sudo git --git-dir=$HOME/.dotfiles --work-tree=$HOME; }
gita() { git add $@; }
gitc() { git commit $@; }
gitp() { git push $@; }
xmodmap() {
    if [ -z "$1" ];then
        sudo xmodmap $HOME/.config/X11/xmodmap
    else
        xmodmap $1
    fi
}
flameshot() {
    if [ -z "$1" ];then
        flameshot launcher
    else
        flameshot "$1"
    fi
}
so() {
    if [ -z "$1" ];then
        source "$HOME/.bashrc"
    else
        source "$1"
    fi
}
# let shell scripts use these functions
export -f dot sudot gita gitc gitp so
