#!/bin/bash

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/markiep/.local/share/conda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/markiep/.local/share/conda/etc/profile.d/conda.sh" ]; then
        . "/home/markiep/.local/share/conda/etc/profile.d/conda.sh"
    else
        export PATH="/home/markiep/.local/share/conda/bin:$PATH"
    fi
fi
unset __conda_setup
conda deactivate
# <<< conda initialize <<<

