#!/bin/bash

# Set env vars
export EDITOR="nvim"
export INPUTRC="$HOME/.config/inputrc"
export GOPATH="$HOME/.local/share/go"
export PATH="$PATH:$HOME/.local/bin/:$GOPATH/bin:$HOME/.cargo/bin"
# default prompt
export PS1="[\u@\h \W]\$ "
# set the max pwd history
export DIRSTACKMAX="100"
export GNUPLOT_LIB="/usr/share/gnuplot/5.4/gnuplotrc:$HOME/.config/gnuplot/gnuplot.conf"
export nl="
"

