#!/bin/bash
# set my terminal prompt
source /usr/share/git/completion/git-prompt.sh

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}

export PS1="\n\[\e[36m\][\t]\[\e[00m\]:\[\e[32m\][\u@\h]\[\e[00m\]:\[\e[35m\][$(__git_ps1 '%s')]\\n \[\e[33m\]\w> \[\e[00m\]"
