#!/bin/bash
# set shell shortcuts

## Shortcuts
cfg="$HOME/.config/"
pics="$HOME/media/pics/"
vids="$HOME/media/vids/"
audio="$HOME/media/audio/"
dl="$HOME/tmp/downloads/"
gh="$HOME/.github/"

sc="$HOME/src/"
scr="$HOME/src/repos/"
sce="$HOME/src/external/"
scp="$HOME/src/personal/"
sct="$HOME/src/template/"

fc="$HOME/files/freeCAD/"
gd="$HOME/files/godot/"
bd="$HOME/files/blender/"
mc="$HOME/files/minecraft/"

nt="$HOME/notes/"
nts="$HOME/notes/src/"
nto="$HOME/notes/org/"
todo="$HOME/notes/org/TODO.org"
alias todo="$EDITOR $todo"

nv="$HOME/.config/nvim/"
nvc="$HOME/.config/nvim/cfg/"
nvp="$HOME/.config/nvim/plugcfg/"
nvd="$HOME/.local/share/nvim/"
