#!/bin/sh
# file & directory shortcuts

cfg="$XDG_CONFIG_HOME"
dl="$HOME/tmp"

media="$HOME/media"
imgs="$media/imgs"
screen="$imgs/screen"
vids="$media/vids"
audio="$media/audio"
music="$audio/music"
doc="$media/doc"
study="$doc/study"

src="$HOME/src"
sl="$src/local"
sr="$src/repos"
st="$src/template"

nt="$HOME/notes"
ntd="$nt/dev"
nto="$nt/org"
todo="$nto/TODO"
alias todo="$EDITOR $todo"

nv="$cfg/nvim"
nvi="$nv/init.lua"
nvd="$XDG_DATA_HOME/nvim"

